import type { Recipe } from '../types';

export const recipes: Recipe[] = [
  {
    id: 1,
    title: 'Satu Klik ke MVP Landing Page',
    category: 'frontend',
    difficulty: 'Pemula',
    time: '5 min',
    rating: 4.9,
    reviews: 234,
    feature: 'Image-to-App',
    description: 'Upload sketch tangan dan dapatkan kode HTML/CSS/JS siap pakai',
    trending: true,
    likes: 1234,
    views: 5678,
    completions: 892,
    tags: ['HTML', 'CSS', 'JavaScript', 'Responsive'],
    author: 'Sarah Chen',
    verified: true
  },
  {
    id: 2,
    title: 'Perbaikan Bug Memory Leak Otomatis',
    category: 'debugging',
    difficulty: 'Menengah',
    time: '3 min',
    rating: 4.8,
    reviews: 189,
    feature: 'AI Debugging',
    description: 'Identifikasi dan perbaiki memory leak dengan AI analysis',
    likes: 987,
    views: 3456,
    completions: 654,
    tags: ['Debugging', 'Performance', 'Memory'],
    author: 'Mike Johnson',
    verified: true
  },
  {
    id: 3,
    title: 'Migrasi Python 2 ke Python 3 dalam 3 Detik',
    category: 'migration',
    difficulty: 'Menengah',
    time: '3 min',
    rating: 4.7,
    reviews: 156,
    feature: 'Code Migration',
    description: 'Update syntax dan best practices ke versi terbaru secara otomatis',
    likes: 756,
    views: 2890,
    completions: 543,
    tags: ['Python', 'Migration', 'Refactoring'],
    author: 'Alex Wong'
  },
  {
    id: 4,
    title: 'Sistem Authentication Lengkap MERN',
    category: 'fullstack',
    difficulty: 'Lanjut',
    time: '10 min',
    rating: 5.0,
    reviews: 312,
    feature: 'Full-Stack Agent',
    description: 'Generate frontend dan backend authentication dalam satu prompt',
    trending: true,
    likes: 2341,
    views: 8765,
    completions: 1234,
    tags: ['React', 'Node.js', 'MongoDB', 'JWT'],
    author: 'David Kim',
    verified: true
  },
  {
    id: 5,
    title: 'Figma Design ke React Component',
    category: 'frontend',
    difficulty: 'Pemula',
    time: '4 min',
    rating: 4.9,
    reviews: 278,
    feature: 'Image-to-App',
    description: 'Konversi design Figma menjadi komponen React yang berfungsi',
    likes: 1567,
    views: 6789,
    completions: 1001,
    tags: ['React', 'Figma', 'Components'],
    author: 'Emma Davis',
    verified: true
  },
  {
    id: 6,
    title: 'API Integration Generator',
    category: 'backend',
    difficulty: 'Menengah',
    time: '7 min',
    rating: 4.6,
    reviews: 143,
    feature: 'CLI Agent',
    description: 'Generate API endpoints dan integration code otomatis',
    likes: 678,
    views: 2345,
    completions: 456,
    tags: ['API', 'REST', 'Integration'],
    author: 'Tom Wilson'
  }
];

